export const headerNav = [
    {
        id: 0,
        name: "Strona główna",
        path: "/",
    },
    {
        id: 1,
        name: "Wyszukiwarka produktów",
        path: "/add-meal"
    },
    {
        id: 2,
        name: "Planowanie diety",
        path: "/planningDiets"
    },
    {
        id: 3,
        name: "Kalkulatory",
        path: "/calculators"
    }
]



export const foodData = [
    {
        id: 0,
        name: "Chleb Baranowicki",
        kcal: 247,
        proteins: 7.5,
        carbs: 55,
        fats: 1.5,
    },
    {
        id: 1,
        name: "Poledwica sopocka - morliny",
        kcal: 200,
        proteins: 7.5,
        carbs: 55,
        fats: 1.5,
    },
    {
        id: 2,
        name: "Szynka",
        kcal: 96,
        proteins: 17,
        carbs: 0,
        fats: 3,
    },
    {
        id: 3,
        name: "Wędlina z piersi indyka",
        kcal: 90,
        proteins: 19.1,
        carbs: 1.9,
        fats: 0.7,
    },
    {
        id: 4,
        name: "Pierś z kurczaka",
        kcal: 79,
        proteins: 16.8,
        carbs: 2.2,
        fats: 0.4,
    },
    {
        id: 5,
        name: "Poledwica łososiowa",
        kcal: 102,
        proteins: 21,
        carbs: 0.8,
        fats: 1.6,
    },
    {
        id: 6,
        name: "Kurczak (udo bez skóry i kości)",
        kcal: 125,
        proteins: 17.8,
        carbs: 0,
        fats: 6,
    },
    {
        id: 7,
        name: "Mięso mielone drobiowe",
        kcal: 143,
        proteins: 19,
        carbs: 0,
        fats: 7.5,
    },
    {
        id: 8,
        name: "Kurczak (pierś duszona)",
        kcal: 151,
        proteins: 29,
        carbs: 0,
        fats: 3,
    },
    {
        id: 9,
        name: "Kotlet schabowy panierowany",
        kcal: 318,
        proteins: 15,
        carbs: 11.5,
        fats: 25,
    },
    {
        id: 10,
        name: "Kotlet mielony (smażony)",
        kcal: 254,
        proteins: 18.6,
        carbs: 6.4,
        fats: 17.9,
    },
    {
        id: 11,
        name: "Szynka drobiowa",
        kcal: 123,
        proteins: 18.2,
        carbs: 0,
        fats: 5.6,
    },
    {
        id: 12,
        name: "Schab (pieczony)",
        kcal: 146,
        proteins: 21,
        carbs: 3,
        fats: 5.5,
    },
    {
        id: 13,
        name: "Szynka z piersi kurczaka",
        kcal: 85,
        proteins: 16.2,
        carbs: 1.5,
        fats: 1.6,
    },
    {
        id: 14,
        name: "Filet z kurczaka",
        kcal: 99,
        proteins: 21.5,
        carbs: 0,
        fats: 1.3,
    },
    {
        id: 15,
        name: "Kurczak pieczone udko",
        kcal: 211,
        proteins: 24,
        carbs: 0,
        fats: 12,
    },
    {
        id: 16,
        name: "Indyk(mięso mielone)",
        kcal: 1280,
        proteins: 16.9,
        carbs: 0,
        fats: 12.5,
    },
    {
        id: 17,
        name: "Pierś z kurczaka ugotowana",
        kcal: 151,
        proteins: 32.9,
        carbs: 0,
        fats: 2,
    },
    {
        id: 18,
        name: "Schab(surowy)",
        kcal: 128,
        proteins: 24,
        carbs: 0.4,
        fats: 3.5,
    },
    {
        id: 19,
        name: "Szynka z indyka",
        kcal: 132,
        proteins: 19.6,
        carbs: 0,
        fats: 5.2,
    },
    {
        id: 20,
        name: "Poledwica wieprzowa (wędzona)",
        kcal: 165,
        proteins: 19,
        carbs: 1,
        fats: 9,
    },
    {
        id: 19,
        name: "Kiełbasa podwawelska",
        kcal: 254,
        proteins: 17.3,
        carbs: 0.9,
        fats: 19.6,
    },
    {
        id: 20,
        name: "Parówki berlinki classic",
        kcal: 251,
        proteins: 12.9,
        carbs: 2.7,
        fats: 21,
    },
    {
        id: 21,
        name: "Wołowina(udziec)",
        kcal: 160,
        proteins: 21,
        carbs: 0,
        fats: 7.9,
    },
    {
        id: 22,
        name: "Karkówka wieprzowa z grilla",
        kcal: 389,
        proteins: 23,
        carbs: 0,
        fats: 33,
    },
    {
        id: 23,
        name: "Mięso mielone wołowe",
        kcal: 254,
        proteins: 17,
        carbs: 0,
        fats: 20,
    },
    {
        id: 24,
        name: "Pasztet z drobiu",
        kcal: 149,
        proteins: 21.9,
        carbs: 1.4,
        fats: 5.7,
    },
    {
        id: 25,
        name: "Szynka wieprzowa wędzona",
        kcal: 212,
        proteins: 19,
        carbs: 1.2,
        fats: 14.5,
    },
    {
        id: 26,
        name: "Udo z kurczaka bez skóry (pieczone)",
        kcal: 130,
        proteins: 17.3,
        carbs: 0.8,
        fats: 6.4,
    },
    {
        id: 27,
        name: "Wołowina (polędwica) surowa",
        kcal: 127,
        proteins: 22.3,
        carbs: 0,
        fats: 3.5,
    },
    {
        id: 28,
        name: "Kiełbasa śląska",
        kcal: 214,
        proteins: 17.9,
        carbs: 0,
        fats: 16.1,
    },
    {
        id: 29,
        name: "Kiełbasa szynkowa",
        kcal: 162,
        proteins: 18,
        carbs: 0,
        fats: 10,
    },
    {
        id: 30,
        name: "Kaszanka",
        kcal: 274,
        proteins: 9,
        carbs: 14.5,
        fats: 19.5,
    },
    {
        id: 31,
        name: "Mięso mielone wieprzowe",
        kcal: 264,
        proteins: 21,
        carbs: 0,
        fats: 20,
    },
    {
        id: 32,
        name: "Boczek wędzony",
        kcal: 478,
        proteins: 12.6,
        carbs: 0.7,
        fats: 47,
    },
    {
        id: 33,
        name: "Polędwica drobiowa",
        kcal: 125,
        proteins: 22,
        carbs: 2,
        fats: 4,
    },
    {
        id: 34,
        name: "Kabanos wieprzowy",
        kcal: 328,
        proteins: 28,
        carbs: 0,
        fats: 24,
    },
    {
        id: 35,
        name: "Salami",
        kcal: 459,
        proteins: 22,
        carbs: 0.3,
        fats: 41,
    },
    {
        id: 36,
        name: "Kurczak grillowany",
        kcal: 200,
        proteins: 28.1,
        carbs: 0,
        fats: 9.7,
    },
    {
        id: 37,
        name: "Filet z piersi kurczaka grillowany",
        kcal: 123,
        proteins: 25.8,
        carbs: 0,
        fats: 4.9,
    },
    {
        id: 38,
        name: "Filet wędzony z indyka",
        kcal: 117,
        proteins: 22,
        carbs: 1,
        fats: 2,
    },
    {
        id: 39,
        name: "Indyk (udo bez skóry)",
        kcal: 139,
        proteins: 19.5,
        carbs: 0,
        fats: 6.7,
    },
    {
        id: 40,
        name: "Indyk pieczony",
        kcal: 208,
        proteins: 28.1,
        carbs: 0,
        fats: 9.7,
    },
    {
        id: 41,
        name: "Pierś z kurczaka gotowana na parze",
        kcal: 151,
        proteins: 32.9,
        carbs: 0,
        fats: 2,
    },
    {
        id: 42,
        name: "Boczek smażony",
        kcal: 541,
        proteins: 37,
        carbs: 1.4,
        fats: 41.8,
    },
    {
        id: 43,
        name: "Filet z indyka",
        kcal: 84,
        proteins: 19.2,
        carbs: 0,
        fats: 0.7,
    },
    {
        id: 44,
        name: "Wołowina (mięso bez kości)",
        kcal: 232,
        proteins: 18,
        carbs: 0.4,
        fats: 17.6,
    },
    {
        id: 45,
        name: "Pieczeń wieprzowa",
        kcal: 247,
        proteins: 27,
        carbs: 0,
        fats: 5.5,
    },
    {
        id: 46,
        name: "Pulpety z indyka",
        kcal: 42,
        proteins: 5.5,
        carbs: 1.9,
        fats: 1.2,
    },
    {
        id: 47,
        name: "Szynka konserwowa - Sokołów",
        kcal: 109,
        proteins: 19.1,
        carbs: 1.9,
        fats: 2.8,
    },
    {
        id: 48,
        name: "Mielonka",
        kcal: 171,
        proteins: 19,
        carbs: 0,
        fats: 28.4,
    },
    {
        id: 49,
        name: "Pieczeń rzymska",
        kcal: 149,
        proteins: 17.0,
        carbs: 4.5,
        fats: 6.0,
    },
    {
        id: 50,
        name: "Kotlet mielony",
        kcal: 248,
        proteins: 19.5,
        carbs: 5.9,
        fats: 17.7,
    },
    {
        id: 51,
        name: "Wołowina (rostbef)",
        kcal: 218,
        proteins: 26.4,
        carbs: 0,
        fats: 11.6,
    },
    {
        id: 52,
        name: "Kiełbasa z dzika",
        kcal: 174,
        proteins: 27,
        carbs: 0.2,
        fats: 6.5,
    },
    {
        id: 53,
        name: "Indyk (gotowany)",
        kcal: 139,
        proteins: 22,
        carbs: 0,
        fats: 5.5,
    },
    {
        id: 54,
        name: "Szynka konserwowa - Sokołów",
        kcal: 109,
        proteins: 19.1,
        carbs: 1.9,
        fats: 2.8,
    },
    {
        id: 55,
        name: "Kotlet de volaille",
        kcal: 270,
        proteins: 20,
        carbs: 15.5,
        fats: 15,
    },
    {
        id: 56,
        name: "Kotlet schabowy",
        kcal: 353,
        proteins: 19,
        carbs: 15.5,
        fats: 24,
    },
    {
        id: 57,
        name: "Parówki z indyka",
        kcal: 239,
        proteins: 12,
        carbs: 0.5,
        fats: 20,
    },
    {
        id: 58,
        name: "Boczek grillowany",
        kcal: 185,
        proteins: 24.2,
        carbs: 1.4,
        fats: 8.4,
    },
    {
        id: 59,
        name: "Metka",
        kcal: 135,
        proteins: 14.9,
        carbs: 0.4,
        fats: 8,
    },
    {
        id: 60,
        name: "Udko z kurczaka",
        kcal: 158,
        proteins: 16.8,
        carbs: 0,
        fats: 10.2,
    },
    {
        id: 61,
        name: "Kurczak z rożna",
        kcal: 260,
        proteins: 23,
        carbs: 0,
        fats: 19,
    },
    {
        id: 62,
        name: "Ogonówka parzona",
        kcal: 134,
        proteins: 16.7,
        carbs: 0,
        fats: 7.5,
    },
    {
        id: 63,
        name: "Skrzydełko z kurczaka",
        kcal: 186,
        proteins: 19.2,
        carbs: 0,
        fats: 12.2,
    },
    {
        id: 64,
        name: "Indyk filet bez panierki (smażony)",
        kcal: 135,
        proteins: 26,
        carbs: 0,
        fats: 2.6,
    },
    {
        id: 65,
        name: "Tatar",
        kcal: 118,
        proteins: 17.5,
        carbs: 0.8,
        fats: 5,
    },
    {
        id: 66,
        name: "Salami włoskie",
        kcal: 425,
        proteins: 21.7,
        carbs: 1.2,
        fats: 37,
    },
    {
        id: 67,
        name: "Pierś indycza bez skóry",
        kcal: 104,
        proteins: 17,
        carbs: 4,
        fats: 2,
    },
    {
        id: 68,
        name: "Poledwica drobiowa - JBB",
        kcal: 93,
        proteins: 20,
        carbs: 0,
        fats: 1.2,
    },
    {
        id: 69,
        name: "Żołądki drobiowe",
        kcal: 114,
        proteins: 18.2,
        carbs: 0.6,
        fats: 4.2,
    },
    {
        id: 70,
        name: "activia jogurt naturalny do picia",
        kcal: 54,
        proteins: 3.2,
        carbs: 4.8,
        fats: 2.6,
    },
    {
        id: 71,
        name: "bakoma MEN BIAŁKO",
        kcal: 84,
        proteins: 8,
        carbs: 9,
        fats: 1.8,
    },
    {
        id: 72,
        name: "Białko jaja kurzego",
        kcal: 52,
        proteins: 10.9,
        carbs: 0.7,
        fats: 0.2,
    },
    {
        id: 73,
        name: "Danonki",
        kcal: 107,
        proteins: 6.4,
        carbs: 13.8,
        fats: 2.9,
    },
    {
        id: 74,
        name: "Jajecznica",
        kcal: 149,
        proteins: 10,
        carbs: 1.6,
        fats: 11,
    },
    {
        id: 75,
        name: "Jajecznica na maśle z 2 jaj",
        kcal: 216,
        proteins: 12.7,
        carbs: 1.4,
        fats: 18,
    },
    {
        id: 76,
        name: "Jajecznica z cebulą, pieczarkami i serem",
        kcal: 80,
        proteins: 8,
        carbs: 4,
        fats: 3,
    },
    {
        id: 77,
        name: "Jajko",
        kcal: 145,
        proteins: 14,
        carbs: 0,
        fats: 10,
    },
    {
        id: 78,
        name: "Jajko kurze L",
        kcal: 139,
        proteins: 13,
        carbs: 1,
        fats: 10,
    },
    {
        id: 79,
        name: "Jajo kurze (żółtko)",
        kcal: 322,
        proteins: 15.9,
        carbs: 3.6,
        fats: 26.5,
    },
    {
        id: 80,
        name: "Jogurt grecki - Piątnica",
        kcal: 84,
        proteins: 7,
        carbs: 14,
        fats: 0,
    },
    {
        id: 81,
        name: "Jogurt naturalny 2% tłuszczu",
        kcal: 70,
        proteins: 4.3,
        carbs: 5.2,
        fats: 2,
    },
    {
        id: 82,
        name: "Śmietana 12% tłuszczu",
        kcal: 134,
        proteins: 2.8,
        carbs: 4.3,
        fats: 12,
    },
    {
        id: 83,
        name: "Jogurt naturalny",
        kcal: 69,
        proteins: 4.6,
        carbs: 5.8,
        fats: 3,
    },
    {
        id: 84,
        name: "Ser Gouda",
        kcal: 356,
        proteins: 25,
        carbs: 2.2,
        fats: 27,
    },
    {
        id: 85,
        name: "Serek wiejski lekki - Piątnica",
        kcal: 81,
        proteins: 11,
        carbs: 2.4,
        fats: 3,
    },
    {
        id: 86,
        name: "Ser Mozzarella light",
        kcal: 254,
        proteins: 24.3,
        carbs: 2.8,
        fats: 15.9,
    },
    {
        id: 87,
        name: "Ser Feta",
        kcal: 264,
        proteins: 14.2,
        carbs: 4.1,
        fats: 21.3,
    },
    {
        id: 88,
        name: "Mleko 3,2% tłuszczu",
        kcal: 61,
        proteins: 3.2,
        carbs: 4.8,
        fats: 3.2,
    },
    {
        id: 89,
        name: "Serek śmietankowy - Almette",
        kcal: 230,
        proteins: 7,
        carbs: 6,
        fats: 20,
    },
    {
        id: 90,
        name: "Serek wiejski - Piątnica",
        kcal: 97,
        proteins: 11,
        carbs: 2,
        fats: 5,
    },
    {
        id: 91,
        name: "Jogurt naturalny - Piątnica",
        kcal: 58,
        proteins: 4,
        carbs: 5.9,
        fats: 2,
    },
    {
        id: 92,
        name: "Ser biały półtłusty",
        kcal: 128,
        proteins: 20,
        carbs: 3,
        fats: 4,
    },
    {
        id: 93,
        name: "Ser Mozzarella",
        kcal: 248,
        proteins: 17.5,
        carbs: 1.5,
        fats: 19,
    },
    {
        id: 94,
        name: "Kefir naturalny - Krasnystaw",
        kcal: 57,
        proteins: 4,
        carbs: 5.7,
        fats: 2,
    },
    {
        id: 95,
        name: "Oliwa z oliwek - Monini",
        kcal: 824,
        proteins: 0,
        carbs: 0,
        fats: 92,
    },
    {
        id: 96,
        name: "Serek wiejski - Biedronka",
        kcal: 99,
        proteins: 11,
        carbs: 3,
        fats: 5,
    },
    {
        id: 97,
        name: "Serek z ziołami - Almette",
        kcal: 230,
        proteins: 6.8,
        carbs: 5.6,
        fats: 20,
    },
    {
        id: 98,
        name: "Twaróg",
        kcal: 90,
        proteins: 19,
        carbs: 3.5,
        fats: 0,
    },
    {
        id: 99,
        name: "Jogurt - Piątnica",
        kcal: 57,
        proteins: 8.7,
        carbs: 4.1,
        fats: 0,
    },
    {
        id: 100,
        name: "Masło Polskie - Mlekovita",
        kcal: 746,
        proteins: 1,
        carbs: 1,
        fats: 82,
    },
    {
        id: 101,
        name: "Maślanka",
        kcal: 34,
        proteins: 3.4,
        carbs: 4.9,
        fats: 1.5,
    },
    {
        id: 102,
        name: "Maślanka",
        kcal: 34,
        proteins: 3.4,
        carbs: 4.9,
        fats: 1.5,
    },
    {
        id: 103,
        name: "Ser Edam",
        kcal: 357,
        proteins: 25,
        carbs: 1.4,
        fats: 27.8,
    },
    {
        id: 104,
        name: "Ser Gouda - Światowid",
        kcal: 335,
        proteins: 23,
        carbs: 0.1,
        fats: 27,
    },
    {
        id: 105,
        name: "Ser Camembert",
        kcal: 263,
        proteins: 19.3,
        carbs: 1.9,
        fats: 19.8,
    },
    {
        id: 106,
        name: "Oscypek",
        kcal: 386,
        proteins: 29,
        carbs: 0,
        fats: 30,
    },
    {
        id: 107,
        name: "Maślanka",
        kcal: 34,
        proteins: 3.4,
        carbs: 4.9,
        fats: 1.5,
    },
    {
        id: 108,
        name: "Woda",
        kcal: 0,
        proteins: 0,
        carbs: 0,
        fats: 0,
    },
    {
        id: 109,
        name: "Sok z cytryny",
        kcal: 22,
        proteins: 0.4,
        carbs: 6.9,
        fats: 0.2,
    },
    {
        id: 110,
        name: "Kawa parzona bez cukru",
        kcal: 1,
        proteins: 0.1,
        carbs: 0,
        fats: 0,
    },
    {
        id: 112,
        name: "Kawa z mlekiem (2 łyżki mleka 2%)",
        kcal: 7,
        proteins: 1,
        carbs: 3,
        fats: 1,
    },
    {
        id: 113,
        name: "Herbata (parzona) - Lipton",
        kcal: 4,
        proteins: 0.4,
        carbs: 0,
        fats: 0,
    },
    {
        id: 114,
        name: "Kawa Latte",
        kcal: 33,
        proteins: 2,
        carbs: 3,
        fats: 1.4,
    },
    {
        id: 115,
        name: "Kawa (rozpuszczona)",
        kcal: 2,
        proteins: 0.2,
        carbs: 0.3,
        fats: 0,
    },
    {
        id: 116,
        name: "Kawa Espresso",
        kcal: 2,
        proteins: 0.1,
        carbs: 0,
        fats: 0.2,
    },
    {
        id: 116,
        name: "Wódka",
        kcal: 231,
        proteins: 0,
        carbs: 0,
        fats: 0,
    },
    {
        id: 117,
        name: "Coca Cola",
        kcal: 37,
        proteins: 0.1,
        carbs: 9.6,
        fats: 0,
    },
    {
        id: 118,
        name: "Sok marchwiowy jednodniowy",
        kcal: 37,
        proteins: 0.4,
        carbs: 8.7,
        fats: 0.1,
    },
    {
        id: 119,
        name: "Mleko kokosowe",
        kcal: 119,
        proteins: 0.6,
        carbs: 2.2,
        fats: 12,
    },
    {
        id: 120,
        name: "Sok 100% pomarańcza z miąższem",
        kcal: 43,
        proteins: 0.6,
        carbs: 9.5,
        fats: 0.5,
    },
    {
        id: 121,
        name: "Sok jabłkowy",
        kcal: 46,
        proteins: 0.1,
        carbs: 11.3,
        fats: 0.1,
    },
    {
        id: 122,
        name: "Whisky",
        kcal: 220,
        proteins: 0,
        carbs: 0,
        fats: 0,
    },
    {
        id: 123,
        name: "Pepsi Cola",
        kcal: 37,
        proteins: 0.1,
        carbs: 9.6,
        fats: 0,
    },
    {
        id: 124,
        name: "Mleko migdałowe - Alpro",
        kcal: 24,
        proteins: 1,
        carbs: 3,
        fats: 1,
    },
    {
        id: 125,
        name: "Wino białe półsłodkie",
        kcal: 82,
        proteins: 0.1,
        carbs: 3.1,
        fats: 0,
    },
    {
        id: 126,
        name: "Wino białe półwytrawne",
        kcal: 0,
        proteins: 0,
        carbs: 3.7,
        fats: 0,
    },
    {
        id: 127,
        name: "Cydr jabłkowy",
        kcal: 47,
        proteins: 0,
        carbs: 12,
        fats: 0.2,
    },
    {
        id: 128,
        name: "Syrop malinowy",
        kcal: 215,
        proteins: 0,
        carbs: 53,
        fats: 0,
    },
    {
        id: 129,
        name: "Piwo ciemne pełne",
        kcal: 68,
        proteins: 0,
        carbs: 4.5,
        fats: 0,
    },
    {
        id: 130,
        name: "Red Bull",
        kcal: 45,
        proteins: 0.3,
        carbs: 10.9,
        fats: 0.1,
    },
    {
        id: 131,
        name: "Banan",
        kcal: 89,
        proteins: 1,
        carbs: 22,
        fats: 0.3,
    },
    {
        id: 132,
        name: "Jabłko (świeży owoc)",
        kcal: 57,
        proteins: 0.3,
        carbs: 13.8,
        fats: 0.2,
    },
    {
        id: 133,
        name: "Awokado",
        kcal: 160,
        proteins: 2,
        carbs: 8.5,
        fats: 15,
    },
    {
        id: 134,
        name: "Kiwi",
        kcal: 61,
        proteins: 1.1,
        carbs: 14.7,
        fats: 0.5,
    },
    {
        id: 135,
        name: "Pomarańcza",
        kcal: 53,
        proteins: 0.9,
        carbs: 15.5,
        fats: 0.3,
    },
    {
        id: 136,
        name: "Rodzynki",
        kcal: 299,
        proteins: 3.1,
        carbs: 79.2,
        fats: 0.5,
    },
    {
        id: 137,
        name: "Truskawki",
        kcal: 32,
        proteins: 0.7,
        carbs: 7.7,
        fats: 0.3,
    },
    {
        id: 138,
        name: "Orzechy włoskie",
        kcal: 645,
        proteins: 16.0,
        carbs: 18,
        fats: 60.3,
    },
    {
        id: 139,
        name: "Oliwki zielone",
        kcal: 145,
        proteins: 1,
        carbs: 3.8,
        fats: 15.3,
    },
    {
        id: 140,
        name: "Cytryna",
        kcal: 29,
        proteins: 1.1,
        carbs: 9,
        fats: 0.3,
    },
    {
        id: 141,
        name: "Brzoskwinia",
        kcal: 39,
        proteins: 0.9,
        carbs: 9.5,
        fats: 0.3,
    },
    {
        id: 141,
        name: "Pomidor",
        kcal: 18,
        proteins: 0.9,
        carbs: 3.9,
        fats: 0.2,
    },
    {
        id: 142,
        name: "Czosnek",
        kcal: 152,
        proteins: 6.4,
        carbs: 32.6,
        fats: 0.5,
    },
    {
        id: 143,
        name: "Ogórek",
        kcal: 15,
        proteins: 15,
        carbs: 0.7,
        fats: 0.1,
    },
    {
        id: 144,
        name: "Papryka czerwona",
        kcal: 28,
        proteins: 1.3,
        carbs: 6.6,
        fats: 0.5,
    },
    {
        id: 145,
        name: "Ziemniaki",
        kcal: 77,
        proteins: 1.9,
        carbs: 18.5,
        fats: 0.1,
    },
    {
        id: 146,
        name: "Ogórek kiszony",
        kcal: 11,
        proteins: 0.3,
        carbs: 2.3,
        fats: 0.2,
    },
    {
        id: 147,
        name: "Szczypiorek",
        kcal: 35,
        proteins: 4.1,
        carbs: 4.2,
        fats: 0.8,
    },
    {
        id: 148,
        name: "Szpinak świeży",
        kcal: 23,
        proteins: 2.9,
        carbs: 3.6,
        fats: 0.4,
    },
    {
        id: 149,
        name: "Pomidor koktajlowy",
        kcal: 18,
        proteins: 1,
        carbs: 4,
        fats: 0.2,
    },
    {
        id: 150,
        name: "Brokuły",
        kcal: 34,
        proteins: 3,
        carbs: 4,
        fats: 0.4,
    },
    {
        id: 151,
        name: "Sałata lodowa",
        kcal: 14,
        proteins: 0.9,
        carbs: 3,
        fats: 0.1,
    },
    {
        id: 152,
        name: "Papryka chili",
        kcal: 40,
        proteins: 2,
        carbs: 8.8,
        fats: 0.4,
    },
    {
        id: 153,
        name: "Pieczarki świeże",
        kcal: 22,
        proteins: 3.1,
        carbs: 3.3,
        fats: 0.3,
    },
    {
        id: 154,
        name: "Kapusta kiszona",
        kcal: 19,
        proteins: 1,
        carbs: 4.3,
        fats: 0.1,
    },
]